name: "run tests"
on:
  [push, pull_request, workflow_dispatch]

jobs:
  perl_tester:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        perl-version:
          - "5.24"
          - "5.26"
          - "5.28"
          - "5.30"
          - "5.32"
          - "5.34"
          - "5.36"

    runs-on: ${{ matrix.os }}
    name: "perl v${{ matrix.perl-version }} on ${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v3
      - name: "Set up perl"
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - name: Install dzil
        run: cpanm --notest Dist::Zilla
      - name: Install authordeps
        run: cpanm --notest $(dzil authordeps --missing)
      - name: Install deps
        run: cpanm --notest $(dzil listdeps --missing)
      - name: Test
        run: dzil test
